version: '3.6'

services:
  nginx:
    build: ./containers/nginx
    image: customnginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./statics:/data/statics
    - ./keys:/data/keys
    - ./sites:/etc/nginx/sites-enabled
    - logs:/var/logs/nginx
    restart: always
    networks:
    - nginx-internal

  nodeapi:
    build: ./containers/node
    image: nodeapi
    env_file:
    - discord_application.env
    restart: always
    networks:
    - nginx-internal
  
  haste:
    build: ./containers/haste
    image: haste
    ports:
    - "7777:7777"
    environment:
    - PGHOST=postgres
    env_file:
    - postgres.env
    restart: always
    depends_on:
    - postgres
    networks:
    - postgresdb
    - nginx-internal
    
  postgres:
    image: postgres:10-alpine
    env_file:
    - postgres.env
    restart: always
    volumes:
    - dbstore:/var/lib/postgresql/data
    networks:
    - postgresdb

volumes:
  logs:
  dbstore:

networks:
  postgresdb:
  nginx-internal: